packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.15
  '@platforma-sdk/model': ^1.22.59
  '@platforma-sdk/ui-vue': ^1.22.59
  '@platforma-sdk/tengo-builder': ^1.17.7
  '@platforma-sdk/workflow-tengo': ^2.13.5
  '@platforma-sdk/eslint-config': ^1.0.1

  '@platforma-sdk/test': ^1.22.63
  '@milaboratories/graph-maker': ^1.1.49
  '@milaboratories/software-pframes-conv': ^2.1.12
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.13
  '@platforma-open/milaboratories.software-subread': ^1.0.0
  '@platforma-open/milaboratories.software-star': ^1.0.1
  '@platforma-open/milaboratories.star-read-mapping.genome-assets': ^1.1.6
  '@platforma-open/milaboratories.runenv-r': ^1.2.18
  '@platforma-sdk/package-builder': ^2.15.1

  '@milaboratories/helpers': ^1.6.11

  'ag-grid-enterprise': &ag-grid ^33.1.1
  'ag-grid-vue3': *ag-grid

  'vue': ^3.5.13
  'vue-tsc': ^2.2.4

  'typescript': ~5.5.4
  'tsup': ~8.3.5
  'turbo': ^2.3.3

  'vite': ^6.0.7
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.28.1
