packages:
- software
- workflow
- model
- ui
- block
- test

catalog:
  '@platforma-sdk/block-tools': ^2.6.20
  '@platforma-sdk/model': ^1.45.26
  '@platforma-sdk/ui-vue': ^1.45.29
  '@platforma-sdk/tengo-builder': ^2.3.8
  '@platforma-sdk/workflow-tengo': ^5.5.17
  '@platforma-sdk/eslint-config': ^1.1.0

  '@platforma-sdk/test': ^1.45.29
  '@milaboratories/graph-maker': ^1.1.179

  '@milaboratories/software-pframes-conv': ^2.2.9
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.23
  '@platforma-open/milaboratories.software-subread': ^1.0.2
  '@platforma-open/milaboratories.software-star': ^1.1.1
  '@platforma-open/milaboratories.genome-assets': 1.2.0
  '@platforma-open/milaboratories.runenv-r-normalize-counts': ^1.0.6
  '@platforma-open/milaboratories.runenv-r-sample-qc': ^1.0.5
  '@platforma-sdk/package-builder': ^3.10.7
  '@platforma-sdk/blocks-deps-updater': ^2.0.0

  '@milaboratories/helpers': ^1.12.0

  'ag-grid-enterprise': &ag-grid ~34.1.2
  'ag-grid-vue3': *ag-grid

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'typescript': ~5.5.4
  'tsup': ~8.4.0
  'turbo': ^2.4.4

  'vite': ^6.2.2
  'vitest': ^3.0.8
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.28.1
