packages:
  - workflow
  - model
  - ui
  - pl-table
  - .
  - test

catalog:
  "@milaboratory/tengo-template-builder": ^1.13.0
  "@milaboratory/pl-block-tools": ^2.1.5
  "@milaboratory/block-builder": ^1.2.3

  "@milaboratory/tengo-sdk": ^1.1.7
  "@milaboratory/sdk-ui": ^0.12.20
  "@milaboratory/sdk-test": ^1.4.0

  "@milaboratory/platforma-uikit": ^1.0.14
  "@milaboratory/graph-maker": ^0.0.41
  "@milaboratory/sdk-vue": ^1.0.42
  "@milaboratory/helpers": ^1.4.0
  "@milaboratory/pframes-conv": ^0.4.25

  "vue": ^3.4.34
  "vue-tsc": ^2.0.29

  "zod": ^3.23.8

  "typescript": ^5.5.4
  "tsup": ~8.1.2

  "vite": ^5.3.5
  "vitest": ^2.0.4
  "@vitejs/plugin-vue": ^5.1.0

  "@changesets/cli": ^2.27.7
