packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.1
  '@platforma-sdk/model': ^1.20.27
  '@platforma-sdk/ui-vue': ^1.20.30
  '@platforma-sdk/tengo-builder': ^1.17.5
  '@platforma-sdk/workflow-tengo': ^2.9.5

  '@platforma-sdk/test': ^1.20.27
  '@milaboratories/graph-maker': ^1.1.18
  '@milaboratories/software-pframes-conv': ^2.1.2
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.6
  '@platforma-open/milaboratories.software-subread': ^1.0.0
  '@platforma-open/milaboratories.software-star': ^1.0.1
  '@platforma-open/milaboratories.star-read-mapping.genome-assets': ^1.1.6
  '@platforma-open/milaboratories.runenv-r': ^1.2.9
  '@platforma-sdk/package-builder': ^2.14.2

  '@milaboratories/helpers': ^1.6.11

  'ag-grid-enterprise': &ag-grid ^33.0.3
  'ag-grid-vue3': *ag-grid

  'vue': ^3.5.13
  'vue-tsc': ^2.1.10

  'typescript': ~5.6.3
  'tsup': ~8.3.5
  'turbo': ^2.3.3

  'vite': ^6.0.4
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.27.11
