packages:
  - software
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/block-tools': ^2.5.18
  '@platforma-sdk/model': ^1.22.59
  '@platforma-sdk/ui-vue': ^1.22.64
  '@platforma-sdk/tengo-builder': ^1.19.1
  '@platforma-sdk/workflow-tengo': ^2.15.2
  '@platforma-sdk/eslint-config': ^1.0.1

  '@platforma-sdk/test': ^1.22.77
  '@milaboratories/graph-maker': ^1.1.51

  '@milaboratories/software-pframes-conv': ^2.1.13
  '@platforma-open/milaboratories.software-small-binaries': ^1.15.13
  '@platforma-open/milaboratories.software-subread': ^1.0.0
  '@platforma-open/milaboratories.software-star': ^1.0.1
  '@platforma-open/milaboratories.genome-assets': 1.2.0
  '@platforma-open/milaboratories.runenv-r-normalize-counts': ^1.0.3
  '@platforma-open/milaboratories.runenv-r-sample-qc': ^1.0.3
  '@platforma-sdk/package-builder': ^2.15.2

  '@milaboratories/helpers': ^1.6.11

  'ag-grid-enterprise': &ag-grid ^33.1.1
  'ag-grid-vue3': *ag-grid

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'typescript': ~5.5.4
  'tsup': ~8.3.5
  'turbo': ^2.4.4

  'vite': ^6.2.1
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.28.1
