packages:
  - workflow
  - model
  - ui
  - test
  - .
  
catalog:
  '@platforma-sdk/block-tools': ^2.3.21
  '@platforma-sdk/model': ^1.7.20
  '@platforma-sdk/ui-vue': ^1.7.51
  '@platforma-sdk/tengo-builder': ^1.16.1
  '@platforma-sdk/workflow-tengo': ^1.7.2

  "@platforma-sdk/test": ^1.5.43
  '@milaboratories/graph-maker': ^1.0.20
  '@milaboratories/software-pframes-conv': ^1.6.4
  '@platforma-open/milaboratories.software-small-binaries': ^1.13.1
  '@platforma-open/milaboratories.star-read-mapping.genome-asset': ^1.0.5

  '@ag-grid-community/core': ^32.2.2
  '@ag-grid-community/client-side-row-model': ^32.2.2
  '@ag-grid-community/vue3': ^32.2.2
  '@ag-grid-community/styles': ^32.2.2

  "vue": ^3.4.34
  "vue-tsc": ^2.0.29

  "typescript": ^5.5.4
  "tsup": ~8.1.2

  "vite": ^5.3.5
  "vitest": ^2.0.4
  "@vitejs/plugin-vue": ^5.1.0

  "@changesets/cli": ^2.27.7
