packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  "@platforma-sdk/tengo-builder": ^1.14.11
  "@platforma-sdk/block-tools": ^2.3.4

  "@platforma-sdk/workflow-tengo": ^1.2.10
  "@platforma-sdk/model": ^1.2.28
  "@platforma-sdk/test": ^1.5.25

  "@milaboratories/uikit": ^1.2.7
  "@milaboratories/graph-maker": ^1.0.4
  "@platforma-sdk/ui-vue": ^1.3.11
  "@milaboratories/helpers": ^1.6.2
  "@milaboratories/software-pframes-conv": ^1.5.6

  "@ag-grid-community/core": ^32.2.1
  "@ag-grid-community/vue3": ^32.2.1
  "@ag-grid-community/styles": ^32.2.1
  "@ag-grid-community/client-side-row-model": ^32.2.1
  "@ag-grid-community/infinite-row-model": ^32.2.1
  "@ag-grid-enterprise/clipboard": ^32.2.1
  "@ag-grid-enterprise/range-selection": ^32.2.1

  "vue": ^3.5.10
  "vue-tsc": ^2.1.6

  "zod": ^3.23.8

  "typescript": ~5.5.4
  "tsup": ~8.1.2

  "vite": ^5.4.8
  "vitest": ^2.1.1
  "@vitejs/plugin-vue": ^5.1.4

  "@changesets/cli": ^2.27.7
